package com.smartstudy.compiler.util;

/**
 * <p>
 * Created by Cheney on 2017/1/12.
 */
public class Consts {
    public static final String OPTION_MODULE_NAME = "moduleName";
    public static final String CLASS_JAVA_DOC = "Generated by Router. Do not edit it!\n";

    public static final String ACTIVITY_FULL_NAME = "android.app.Activity";
    public static final String FRAGMENT_FULL_NAME = "android.app.Fragment";
    public static final String FRAGMENT_V4_FULL_NAME = "android.support.v4.app.Fragment";

    public static final String ROUTE_ANNOTATION_TYPE = "com.smartstudy.annotation.Route";
    public static final String INTERCEPTOR_ANNOTATION_TYPE = "com.smartstudy.annotation.Interceptor";

    public static final String PACKAGE_NAME = "com.smartstudy.router";

    public static final String METHOD_HANDLE = "handle";

    public static final String ROUTE_TABLE = "RouteTable";
    public static final String ROUTE_TABLE_FULL_NAME = PACKAGE_NAME + ".template." + ROUTE_TABLE;

    public static final String INTERCEPTOR_FULL_NAME = PACKAGE_NAME + ".RouteInterceptor";

    public static final String INTERCEPTOR_TABLE = "InterceptorTable";
    public static final String INTERCEPTOR_TABLE_FULL_NAME = PACKAGE_NAME + ".template." + INTERCEPTOR_TABLE;

    public static final String TARGET_INTERCEPTORS_TABLE = "TargetInterceptorsTable";
    public static final String TARGET_INTERCEPTORS_FULL_NAME = PACKAGE_NAME + ".template." + TARGET_INTERCEPTORS_TABLE;

}
